name: Static Analysis

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  static-analysis:
    name: Run Static Analysis
    uses: nasa/cFS/.github/workflows/static-analysis-reusable.yml@dev
    with:
      strict-dir-list: 'source/src/bsp source/src/os'
      cmake-project-options: -DENABLE_UNIT_TESTS=TRUE -DOSAL_OMIT_DEPRECATED=TRUE -DOSAL_SYSTEM_BSPTYPE=generic-linux
